### ISSUE TITLE
Add operators to support common pattern of files being continually dropped into a folder for processing

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.plumbing#10]
Add composite operators that support:

Combination of a DirectoryScan and FileSource to read, process and delete files being dropped into a directory by a data provider, including support in a consistent region.

A composite that generates such files from a stream to allow simulation of the data provider, or output of a Streams application to a different system that processes files the same way.

**Comment by markheger** [comment]
no demand for long time
