### ISSUE TITLE
Nominate ddebrunner as committer

### ISSUE THREAD

**Issue by scotts** [IBMStreams/streamsx.plumbing#17]
I am nominating @ddebrunner as a committer. More than half of the contributions to the toolkit have come from Dan.

**Comment by chanskw** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
Thanks!  Added @ddebrunner as committer.

**Comment by ddebrunner** [comment]
Thanks!
