### ISSUE TITLE
ExpiredTupleDetector metrics

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.plumbing#47]
Be good to have metrics for this operator:

At least
- number of tuples currently help by operator

Maybe oldest timestamp?

**Comment by nysenthil** [comment]
In PR 48 (Waiting to be merged), I added the following two custom metrics for this operator. I tested it and those two values are getting updated.

      <metrics>
        <metric>
          <name>nWaitingForExpiration</name>
          <description>The number of tuples currently being held in the memory of the `ExpiredTupleDetector` operator.</description>
          <kind>Counter</kind>
        </metric>
        <metric>
          <name>nCurrentExpireTime</name>
          <description>Current expireTime setting being used by the `ExpiredTupleDetector` operator.</description>
          <kind>Gauge</kind>
        </metric>
      </metrics>

**Comment by ddebrunner** [comment]
Is "expireTime" really "time to live" (TTL)?

Just I read "expire time" as a point in time, not a period. 

I just wonder if use of a standard term TTL would be better?

**Comment by nysenthil** [comment]
After discussing with Dan, references to expireTime and TTL were changed to 'delay'.
