### ISSUE TITLE
Select namespace for ExpiredTupleDetector..

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.plumbing#49]
Not sure the existing namespace `com.ibm.streamsx.plumbing.expiredtupledetector` is correct.

Looking at the existing names something along the lines of:

- `com.ibm.streamsx.plumbing.delay`
- `com.ibm.streamsx.plumbing.expire`

seem better, somewhat depends on a good crisp definition of what the operator does.
(see comments in #48 )

**Comment by nysenthil** [comment]
Excellent suggestion. Changed the namespace to com.ibm.streamsx.plumbing.delay.
