### ISSUE TITLE
Agedmap functions are in the wrong namespace.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.plumbing#56]
Functions end up being defined in `com.ibm.streamsx.plumbing.delay.com.ibm.streamsx.plumbing.agedmap`.

**Comment by ddebrunner** [comment]
Either they should move to `com.ibm.streamsx.plumbing.agedmap` or be removed and just be private C++ functions for the `KeyedDelay` operator.

**Comment by markheger** [comment]
solved with #57
